### ISSUE TITLE
Create a beautiful Navigation bar on index page.

### ISSUE THREAD

**Issue by amanjha8100** [gdscjgec/UpTrend#2]
## 🚀 Feature

Problem Statement
I would like the contributor to create a beautiful navigation bar with space for categories section.

Solution
Create a attractive navigation bar with categories (choices field) , home, etc.

**Comment by Saup21** [comment]
I would like to work on this issue.

**Comment by rajatkeshri** [comment]
Hi,
I would like to work on this issue

**Comment by mihir1739** [comment]
Please assign me this issue..

**Comment by niloysikdar** [comment]
Assigned you @rajatkeshri
